# Generated by Django 4.0.5 on 2022-06-27 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_imagepost_delete_postimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepost',
            old_name='post_image',
            new_name='post_images',
        ),
        migrations.RenameField(
            model_name='imagepost',
            old_name='title',
            new_name='post_title',
        ),
    ]
