# Generated by Django 4.0.5 on 2022-06-27 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0006_imagepost_titlea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepost',
            old_name='titlea',
            new_name='title',
        ),
    ]
