# Generated by Django 4.0.5 on 2022-09-18 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_alter_post_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepost',
            old_name='post_title',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='imagepost',
            name='post_images',
        ),
        migrations.RemoveField(
            model_name='imagepost',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
        migrations.AddField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(default=12, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
